### ISSUE TITLE
Can't find bluetooth ID

### ISSUE THREAD

**Issue by viictor924** [zwaldowski/homebridge-satellite-fan#4]
Hey! 

First of all, thanks for the homebridge plugin! I've got the same MR101F module so this is really helpful!

I installed your plugin but I don't know where to find the bluetooth info:
- Bluetooth address
- ServiceUUID
- WriteCharacteristicUUID
- NotifyCharacteristicUUID

I looked in the Fan Smart Sync app settings but I can't find it there. I'm afraid it might be printed on the receiver label but I wanted to check with you first since disassembling my ceiling fan is a huge pain.

Thanks!
Victor

**Comment by viictor924** [comment]
Nevermind, I think I was able to find them by using the BLE Scanner 4.0 app on the app store. 

This is what I used
Device UUID (Bluetooth address): 26237ADF-94B8-5D1C-6FBD-735673AF78F0
ServiceUUID: 539C6813-61A0-2137-4F79-BF1A11984790
WriteCharacteristicUUID:    539C6813-61A1-2137-4F79-BF1A11984790
NotifyCharacteristicUUID:   539C6813-61A2-2137-4F79-BF1A11984790

Note that the bluetooth address on your config-sample.json had this format "00:00:00:00:00:00". Whereas the bluetooth address I found on the BLE app had a "00000000-0000-0000-0000-000000000000" format.

I tried pasting in the same format as the app and the ceiling fan accessories are stuck on "Updating".

I also tried pasting just the 12 digits from the BLE app in your "00:00:00:00:00:00" format but I got the same issue. Accessories are stuck on "Updating".

![screen shot 2017-09-30 at 11 57 57 am](https://user-images.githubusercontent.com/23468631/31048653-aea0fcbc-a5d6-11e7-87a6-2719d971d05c.png)

![img_e94a6532b8bc-1](https://user-images.githubusercontent.com/23468631/31048584-f89c4ff8-a5d4-11e7-9ec4-e5bcf9e9d686.jpeg)

![img_0994](https://user-images.githubusercontent.com/23468631/31048373-a080e49a-a5d0-11e7-9b28-c6a09578fd62.PNG)

**Comment by zwaldowski** [comment]
Holy cow, I wish I had known about that scanner app! I went all the way through decompiling an Android app to figure things out. 😅

I’m getting ready to push an update that fixes every connection issue I currently have — things got really finicky if you had > 1 accessory.

The code currently expects a MAC address for the device. That’s going to be different from the device UUID (yeah, I know). You can use `sudo hcitool scan` on Linux to get a list — mine all had “Fan” in their broadcast name.

Other than that, your Bluetooth service UUIDs line up with mine. I’ll go ahead and drop them into the `config-sample.json` for confusion’s sake.

**Comment by zwaldowski** [comment]
The plugin could ultimately be made to attempt either UUID or MAC, so I’ll consider that a feature request, haha.

**Comment by zwaldowski** [comment]
See https://github.com/zwaldowski/homebridge-satellite-fan/releases/tag/v0.2.0. Make sure you install this latest one and not a cached one using `[sudo] npm install -g homebridge-satellite-fan@latest`, mine was having a lot of trouble and it was frustrating to have the same bugs reappear again.

Please reopen if you have any further troubles, and happy automating!

**Comment by viictor924** [comment]
Hey! Thanks for getting back to me! Yea.. apparently iOS/Android no longer lets developers access the MAC address of a bluetooth device so apps won't display it. I was able to find the Mac Address via the raspberry pi using sudo hcitool scan however, I keep getting this "disconnected" errors. (I assume it's related to the connection issues you've been fixing). 

On a separate note, what is the purpose of the "prefix" entry in the config file?

![image](https://user-images.githubusercontent.com/23468631/31161928-3a798d5c-a88f-11e7-9802-429fb6cb716a.png)

**Comment by zwaldowski** [comment]
Disconnects are a bit of a fact of life with BLE, particularly on the Pi’s chip. It could also be a distance/interference thing. Try the new tag and if it doesn’t help, run Homebridge with `-D` and pass along those sweet, sweet logs.

I couldn’t make much sense of the prefix, it just seemed to be an arbitrary difference between the base model and the one shipped in the US and their corresponding apps.

**Comment by zwaldowski** [comment]
OHHH!!! I dropped a totally un-helpful prefix into the config as a H2GG reference. The one the app uses is 64. The module might be kicking clients that don’t send the right prefix as faux-security. (I’ll update the sample config again, so sorry about that!)
