### ISSUE TITLE
Errors installing homebridge-satellite-fan plugin

### ISSUE THREAD

**Issue by viictor924** [zwaldowski/homebridge-satellite-fan#5]
I tried installing the latest version using [sudo] npm install -g homebridge-satellite-fan@latest and immediately all of my accessories became "unresponding". Even the accessories connected to a different pi running homebridge as well as my hue lights connected to a hue bridge. Bizarre, I have no idea how this plugin/pi could affect other bridges so it might be a coincidence. I've managed to get the Home app to reconnect to the Hue bridge but it doesn't detect any of my two pi's anymore :/

pi1: main homebridge, runs two LED strips + a GPIO plugin. Has been stable since I first installed it ~2 weeks ago.
Pi2: development homebridge, I've been using this pi to test the satellite-fan plugin. 

I uninstalled the satellite-fan plugin as well as uninstalled homebridge on pi1. I reinstalled homebridge and I still can't connect it to the Home app.

I'm also getting this error when I try to install the plugin. 
![image](https://user-images.githubusercontent.com/23468631/31165241-2e46a488-a89f-11e7-95a1-2ca5a490d6d7.png)

I noticed this user had a similar [issue](https://github.com/KraigM/homebridge-harmonyhub/issues/97). So I followed Step 2 in ultramizer's comment. 

I then did "npm install -g homebridge-satellite-fan@latest" plugin without sudo and it worked. However, I get a noble warning for running homebridge without sudo.

![image](https://user-images.githubusercontent.com/23468631/31165549-6322a232-a8a0-11e7-989f-bb84a642b1f3.png)

So this time I ran it with sudo by doing "sudo homebridge" but then I get a message saying "No plugins found." 

It seems that by doing "sudo homebridge" I'm running an instance of homebridge that looks for a config.json in /root/.homebridge/config.json instead of /home/pi/.homebridge
![image](https://user-images.githubusercontent.com/23468631/31165734-03ebcb1c-a8a1-11e7-8c4f-56a4d46fb35c.png)

So I tried to force it to run the config.json in my home directory by doing "sudo homebridge -U /home/pi/.homebridge" but it still says "No plugins found". Although this time it doesn't specify that it looked into /root/.homebridge/config.json
![image](https://user-images.githubusercontent.com/23468631/31165881-8efd94b0-a8a1-11e7-903d-2f91139ff2b0.png)

At this point I realized that I hadn't enabled BLE access via non-root users. So I ran "setcap cap_net_raw+eip /usr/bin/nodejs" but I got the following error:
![image](https://user-images.githubusercontent.com/23468631/31166376-6231f33e-a8a3-11e7-84f3-a4141f022f3a.png)

After some more research I found this on the Noble README
```sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)   ```
![image](https://user-images.githubusercontent.com/23468631/31166421-919eb6f2-a8a3-11e7-94c5-c69d18aba7fa.png)

Success! I can now run homebridge with the satellite-fan plugin and I don't get disconnects every few seconds.
![image](https://user-images.githubusercontent.com/23468631/31166441-9f85ea56-a8a3-11e7-974b-f1be0895ed58.png)

I solved my main installation issue so I think we can close this issue. I figured I should still post this in case anyone else runs into the same problem.

On a less happy note, I still can't add any of my homebridges to the Home app :( So even though homebridge and the satellite-fan plugin seem to be running well I can't actually use it. But I guess I could open another issue for this, although I'm not even sure how to start debugging this one besides just resetting homekit and changing the username/pin on the config file until it works.. Thoughts?

**Comment by viictor924** [comment]
Sigh.. I had to re-install Stretch to try to make this work. Good news is that my Home app detects my homebridge now, but I'm having issues installing the satellite-fan plugin

All the Homebridge installation went smoothly, but I got an error installing these packages when I started the satellite-fan installation:
# apt install nodejs-legacy npm bluetooth bluez libbluetooth-dev libudev-dev libcap2-bin
![image](https://user-images.githubusercontent.com/23468631/31172969-92caa4b6-a8ba-11e7-9e5d-be3ff2741b55.png)

Similarly, I get errors when trying to do "setcap cap_net_raw+eip /usr/bin/nodejs" 


![image](https://user-images.githubusercontent.com/23468631/31173138-3e0a6d34-a8bb-11e7-867c-b3a803211907.png)

Finally, when I run 
`sudo npm install -g homebridge homebridge-satellite-fan@latest`
I get these failures:
![image](https://user-images.githubusercontent.com/23468631/31173508-a8751e52-a8bc-11e7-9810-f704b806a7ba.png)

That being said, even with all those failures the plugin works! I can control my ceiling fan with homebridge!
![image](https://user-images.githubusercontent.com/23468631/31173608-1f5373fc-a8bd-11e7-84e2-4aaf8b3f9f25.png)

**Comment by lukehoersten** [comment]
I'm having the same issue but was unable to use any of your suggested workarounds to progress:

```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/node-v8.9.0-linux-armv6l/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'install',
1 verbose cli   '--global',
1 verbose cli   '--unsafe-perm',
1 verbose cli   'homebridge-satellite-fan@latest' ]
2 info using npm@5.5.1
3 info using node@v8.9.0
4 verbose npm-session f2e9f57888d2283d
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 304 https://registry.npmjs.org/homebridge-satellite-fan 2343ms (from cache)
8 silly pacote tag manifest for homebridge-satellite-fan@latest fetched in 2791ms
9 silly install loadIdealTree
10 silly install cloneCurrentTreeToIdealTree
11 silly install loadShrinkwrap
12 silly install loadAllDepsIntoIdealTree
13 silly resolveWithNewModule homebridge-satellite-fan@0.2.3 checking installable status
14 silly fetchPackageMetaData error for noble@git+https://git@github.com/lockitron/noble.git Command failed: /usr/bin/git clone --depth=1 -q -b master https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-d6db0f86
14 silly fetchPackageMetaData fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d6db0f86': Permission denied
15 verbose stack Error: Command failed: /usr/bin/git clone --depth=1 -q -b master https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-d6db0f86
15 verbose stack fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d6db0f86': Permission denied
15 verbose stack
15 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
15 verbose stack     at emitTwo (events.js:126:13)
15 verbose stack     at ChildProcess.emit (events.js:214:7)
15 verbose stack     at maybeClose (internal/child_process.js:925:16)
15 verbose stack     at Socket.stream.socket.on (internal/child_process.js:346:11)
15 verbose stack     at emitOne (events.js:116:13)
15 verbose stack     at Socket.emit (events.js:211:7)
15 verbose stack     at Pipe._handle.close [as _onclose] (net.js:554:12)
16 verbose cwd /home/pi
17 verbose Linux 4.9.59+
18 verbose argv "/opt/node-v8.9.0-linux-armv6l/bin/node" "/usr/bin/npm" "install" "--global" "--unsafe-perm" "homebridge-satellite-fan@latest"
19 verbose node v8.9.0
20 verbose npm  v5.5.1
21 error code 128
22 error Command failed: /usr/bin/git clone --depth=1 -q -b master https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-d6db0f86
22 error fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-d6db0f86': Permission denied
23 verbose exit [ 1, true ]
```

This is with homebridge installed via `sudo npm i -g --unsafe-perm homebridge`.

I tried chowning the whole node and homebridge to the homebridge user to attempt to get the unprivileged install workaround working but it did not.

Any other suggestions to just get this plugin installed would be great.

**Comment by zwaldowski** [comment]
@lukehoersten  It's not even at the point of checking out this code yet. See [here](https://github.com/KraigM/homebridge-harmonyhub/issues/97#issuecomment-310590007). I will note that I've always had success with the `node` from `apt` on Raspbian and haven't needed to use `--unsafe-perm`. But that link above looks like it'll help. Please file a separate issue with a new log if you're still having trouble. Thanks! 😄

**Comment by lukehoersten** [comment]
Right. Thanks. I’ll try to simplify my setup and see if that helps.
