### ISSUE TITLE
Feature request - Hide fan light icon

### ISSUE THREAD

**Issue by viictor924** [zwaldowski/homebridge-satellite-fan#6]
Hey, satellite-fan plugin is working smoothly now!

Would it be possible to have a boolean in the config.json that will enable/disable interaction with the fan light? I've got hue bulbs in my ceiling fan so the fan light has to be on at all times to transmit power to the hue bulbs. However, it's confusing/redundant to have two light icons in the Home app: one for the hue bulbs and one for the ceiling fan light. I think Apple should give us the ability to show/hide icons in the Home app, but they don't. So I think a fix within the plugin is the only solution. 

It also makes the Home app show "Bedroom light on." at all times even though the hue bulbs are off.
![image](https://user-images.githubusercontent.com/23468631/31198398-008fe15c-a909-11e7-85df-8687ae79a608.png)

**Comment by zwaldowski** [comment]
Whoops, GitHub seems to have not added me as a watcher to my own repository. 😞 This should be an easy add.

**Comment by zwaldowski** [comment]
See [v0.2.2](https://github.com/zwaldowski/homebridge-satellite-fan/releases/tag/v0.2.2). Thanks for your patience. 😅
