### ISSUE TITLE
npm install -g --unsafe-perm homebridge-satellite-fan npm ERR! code 128

### ISSUE THREAD

**Issue by Guzmandius** [zwaldowski/homebridge-satellite-fan#8]
Hey Guys--

New installation on rpi 3b+ with raspbian stretch fully update and upgraded.

Getting this error when attempting to install.  Any ideas? Appreciate the assist!

rpi:~ $ sudo npm install -g --unsafe-perm homebridge-satellite-fan
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone -q https://git@github.com/lockitron/noble.git /root/.npm/_cacache/tmp/git-clone-8d5cf7c0
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-8d5cf7c0': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-06-16T02_17_55_441Z-debug.log

**Comment by zwaldowski** [comment]
[This](https://github.com/KraigM/homebridge-harmonyhub/issues/97#issuecomment-310590007) looks related. Let me know if it helps!

**Comment by Guzmandius** [comment]
Thanks Nick!

So I had to sudo su in the pi prompt.

Then ran sudo npm install -g --unsafe-perm homebridge-satellite-fan.

Seem to do the trick.

Thanks for this awesome plugin, loving the features and connectivity.
